[package]
name = "semaphore_network_hss_bridge_srs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
hex = { version = "0.4", default-features = false, features = ["alloc"] }
num-bigint = "0.4.5"
num-traits = "0.2.19"
halo2curves = "0.6.1"
